---
# Define the hooks to be executed before each commit.
# Documentation: https://pre-commit.com/index.html
default_stages: [commit]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.34.0
    hooks:
      # https://github.com/pre-commit/pre-commit/issues/945
      # binding the version numbers specified in ".pre-commit-config.yaml"
      # to versions in "package.json" isn't supported
      - id: eslint
        additional_dependencies:
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-plugin-brace-rules
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        name: Pretty format XML
        additional_dependencies: ['@prettier/plugin-xml']
        args: [--plugin=@prettier/plugin-xml]
        types: [xml]
        exclude_types: [svg]
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.12
    hooks:
      - id: typos
        args: [--format, brief, --write-changes]
  - repo: https://github.com/errata-ai/vale
    rev: v2.23.0
    hooks:
      # Setup: https://github.com/errata-ai/vale/issues/560
      - id: vale
        name: vale sync
        pass_filenames: false
        args: [sync]
      - id: vale
        args: [--output=line]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.9.0
    hooks:
      - id: yamlfix
