name: Publish Release

on:
  push:
    tags:
      - "*"

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  buildRelease: # Job
    name: Build Release
    runs-on: ubuntu-latest # The type of runner that the job will run on
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python enviroment
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.5

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitignore_parser

      - name: Create pyromod and zip files
        run: |
          python .github/build_scripts/make_pyromod.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.PYROMOD_MOD_NAME }} v${{ env.PYROMOD_MOD_VERSION }}
          tag_name: v${{ env.PYROMOD_MOD_VERSION }}
          files: |
            ${{ env.PYROMOD_PYROMOD_FILE_PATH }}
            ${{ env.PYROMOD_ZIP_FILE_PATH }}
